# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8274fea2084be7358e018b6b47a29c1668d75548817d29fc19a0cb920f901129bc90831c8f67170d42e066a0dd2558283d9fd6e80a43a9860cd0c0ed52b2f835

test:
  secret_key_base: 5243b9b7f41534c9ea40c8c598b6fdd053f8552f4ac40a39b702918ef0fbb56b0efd6c70267ba04457a7725f0fc345515d72b9f725914555af9a66f8dc5b89fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
